version: '3'

services:
  server:
    container_name: redis_server
    image: redis
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
