version: '3'

services:
  featune_dev:
    container_name: redis_featune_dev
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6380
    volumes:
      - ./data/featune_dev:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  featune_beta:
    container_name: redis_featune_beta
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6381
    volumes:
      - ./data/featune_beta:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  featune_prod:
    container_name: redis_featune_prod
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6382
    volumes:
      - ./data/featune_prod:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
