version: '3'

services:
  server:
    container_name: redis_server
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
